### ISSUE TITLE
Show promotion modal based on player color

### ISSUE THREAD

**Issue by miradnan** [grzegorz103/ngx-chess-board#163]
@grzegorz103 I have created a PR with added functionality to show promotion modal based on current player colour and show promotion pieces based on player colour.

Here is the PR link. Please merge
https://github.com/grzegorz103/ngx-chess-board/pull/162/

**Comment by grzegorz103** [comment]
Done, thanks

**Comment by miradnan** [comment]
@grzegorz103 thanks for merging. Looks like the pawn promotion modal shows up for both users. Is there a way we can restrict the modal to the user, whose pawn is being promoted? I did add a condition in the engine-facade (line 481), but that doesn't seem to be working as expected. Any thoughts and ideas around this?

https://github.com/grzegorz103/ngx-chess-board/blob/master/projects/ngx-chess-board/src/lib/engine/engine-facade.ts#L481

**Comment by grzegorz103** [comment]
I guess both users have exactly the same state of board. So ```currentPlayer``` and ```board.activePiece.color``` will be the same for them both. I think there are three ways to handle it:
* adding new input to set current context player color and change promotion modal condition based on it. (we have a property ```currentWhitePlayer``` that I mentioned before, but this is just auxiliary field, mostly for calculating possible moves and captures and this field won't fit in this case)
* adding new input, like ```[promotionModalFor]="'black'"```
* there's ```lightDisabled``` and ```darkDisabled``` inputs, and we could show modal based on these fields

It will be a small change, I can make it quickly. Just let me know which option will be better for you.

**Comment by miradnan** [comment]
Options 2 and 3 look good. IMO `lightDisabled` and `darkDisabled` approach should do the fix.

**Comment by grzegorz103** [comment]
Sure, lets make 3. I will refractor and commit it tomorrow, but if you want you can make PR too :)

**Comment by miradnan** [comment]
Sure. I have updated the code. Here is the link https://github.com/grzegorz103/ngx-chess-board/pull/165/

**Comment by grzegorz103** [comment]
Done, thanks.

I merged and bumped version, let me know if this works as expected for you now.

I was considering a condition too something like:
```
        if((piece.color === Color.BLACK && !this.darkDisabled)
            || (piece.color === Color.WHITE && !this.lightDisabled)) {
                   // open modal
       }
```

and then on first board (current white player) we pass ```[darkDisabled]="true"```, and on other board (current black player) we pass ```[lightDisabled]="true"```

Btw, if you have two boards that communicate each other, you may consider ```move(coords: string)``` where you make move manually, it resolves promotion option automatically and doesn't popup modal. I created this method to set moves that I get from back end, maybe it would fit your app well. If you needed help with this I could provide you some examples

**Comment by miradnan** [comment]
@grzegorz103 looks like the issue still persist. Let's try your approach. The promotion modal is opening up for both users, one after the other. Let's say my piece color is black and my pawn is promoted, the promotion modal appears, I then select the piece. Now its white's turn, the promotion modal appears with black pieces. Ideally, only the user whose pawn is being promoted should see the promotion modal. Does the above condition solve for the next move as well?

**Comment by OmarPelcastre** [comment]
I see that the move manually for promotion does not show the modal and that's good but the last character of the input should be the first character of the piece instead of a number, and the output event for moves too. for example 'b7b8q'.

**Comment by OmarPelcastre** [comment]
@miradnan i was sending the FEN position to the other player on promotion moves, you can use that way but the best option is make the manual move

**Comment by grzegorz103** [comment]
You can promote automatically without modal with manual move too,  I forgot to mention it in the docs. 
Add:
* 1 - queen
* 2 - rook
* 3 - bishop
* 4 - knight
to the input move string, so it would be like ```b7a81``` to promote pawn to queen.

So the flow could go like this:
1. Player A moves pawn to promote line, chooses queen from promotion modal
2. Board emits callback with move property ```b7a81```. The promotion option that player A picked is included.
3. Player B receives the move from back end and sends it to the board with ```move(coords: string)``` where coords are the move that player A sent.

Let me know guys if this helps you. @miradnan this flow maybe helps your case? Do you use manual moves?

@OmarPelcastre this is true, this could be first character instead of number, I didn't think about that when I was implementing it. I think it can stay like that now.

**Comment by miradnan** [comment]
@grzegorz103 The logic I have is same as you mentioned above. The move is manual. After the backend sends the move to player B it pops up the promotion modal even though B's pawn is not on the promotion line.

**Comment by grzegorz103** [comment]
I tried to recreate this players' B situation on demo:

Let's say we have this position FEN: rnbqkbnr/ppPppp1p/8/8/8/6p1/P1PPPPPP/RNBQKBNR w KQkq - 0 5
Player B receives move c7b81 (c7 white pawn goes to b8 queen) from backend and makes manual move.

No modal appears

Can you check what move do you send to back end after player A makes promotion move? And what player B receives and passes to the board? It should include the promotion index number, and then the modal shouldn't appear as in this situation above. 

I remember I put a comment on this line because I had exactly issue as you: https://github.com/grzegorz103/ngx-chess-board/blob/b60124204291aebfd4cb844ce14192b0c544dc0c/projects/ngx-chess-board/src/lib/engine/engine-facade.ts#L406

**Comment by miradnan** [comment]
@grzegorz103 @OmarPelcastre Thanks for looking into it. The issue appeared to be with my backend move. I have fixed that and it is working well now. I really appreciate your time and effort in helping out on this.
